New functionality
CiscoUcs/imc-ansible pull request #8
Opened 2017-02-17 19:41 UTC by sandinak

2017-02-17 19:44 UTC, sandinak commented
This has:
- cisco_imc_ipmi - enable and disable ipmi access
- cisco_imc_sol - enable and disable sol on the cimc
- cisco_imc_server - change power state and indicator_led

2017-02-20 00:28 UTC, vvb requested changes
@sandinak thank you for writing up these modules. You have got most of them correct with a minor few nits. I have provided comments where due.

2017-02-20 00:28 UTC, vvb commented on library/cisco_imc_ipmi.py
> +def login(module):
`login` and `logout` are implemented in common code. I see that you are using the below code later. so you can safely remove `login` and `logout` from this file.

```
from ansible.module_utils.cisco_imc import ImcConnection
conn = ImcConnection(module)                                 
server = conn.login()                                                 
conn.logout()
```

2017-02-20 00:28 UTC, vvb commented on library/cisco_imc_ipmi.py
> +def logout(module, imc_server):
same as above

2017-02-20 00:28 UTC, vvb commented on library/cisco_imc_ipmi.py
> +    from imcsdk.apis.admin.ipmi import is_ipmi_enabled
@waghswapnil  this is more of a comment on API layer provided by imcsdk - `is_ipmi_enabled` -> `ipmi_is_enabled`

2017-02-20 00:28 UTC, vvb commented on library/cisco_imc_server.py
> +def login(module):
same as before

2017-02-20 00:28 UTC, vvb commented on library/cisco_imc_server.py
> +def logout(module, imc_server):
same as before

2017-02-20 00:28 UTC, vvb commented on library/cisco_imc_server.py
> +            state=dict(required=False, type='str',
should this be `status`?

2017-02-20 00:28 UTC, vvb commented on library/cisco_imc_server.py
> +    status, locator_led = ansible["status"], ansible["locator_led"]
`locator_led` does not seem to exist in ansible parameters.

2017-02-20 00:28 UTC, vvb commented on library/cisco_imc_server.py
> +                               status, timeout, interval)
where are `timeout` and `interval` coming from?

2017-02-20 00:28 UTC, vvb commented on library/cisco_imc_server.py
> +    if locator_led is not None:
`check_mode` handling is not done here.

2017-02-20 00:28 UTC, vvb commented on library/cisco_imc_sol.py
> +def login(module):
`login` method is not required

2017-02-20 00:28 UTC, vvb commented on library/cisco_imc_sol.py
> +def logout(module, imc_server):
`logout` method is not required

2017-02-20 14:31 UTC, sandinak commented on library/cisco_imc_server.py
> +            state=dict(required=False, type='str',
I don't' believe so.  status implies "position of affairs" .. state implies "particular condition at a time". Most of the ansible modules use 'state' as the moniker: file, service, apt, yum. The only one that uses 'status' AFAIK is the return value of 'stat'.

2017-02-20 14:32 UTC, sandinak commented on library/cisco_imc_ipmi.py
> +    from imcsdk.apis.admin.ipmi import is_ipmi_enabled
Yup .. if it's fixed we should update this as well.

2017-02-20 14:32 UTC, sandinak commented on library/cisco_imc_server.py
> +    status, locator_led = ansible["status"], ansible["locator_led"]
fixed

2017-02-20 14:32 UTC, sandinak commented on library/cisco_imc_server.py
> +                               status, timeout, interval)
fixed and updated docs.

2017-02-20 14:49 UTC, sandinak commented on library/cisco_imc_ipmi.py
> +def login(module):
this was copied directly from cisco_imc_ntp. Probably should be cleaned up as well

2017-02-20 16:55 UTC, vvb commented on library/cisco_imc_server.py
> +            state=dict(required=False, type='str',
well, the original comment was given because there were duplication of `state` variables.. now it makes sense.

2017-02-23 18:52 UTC, merged